### ISSUE TITLE
Graduate debug logs into debug and trace

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingadb#104]
Between the years I accidentally discovered that Logrus has also the log level "trace" below debug.

Look at the debug logs, decide, reason and patch which ones shall be trace ones.

**Comment by dnsmichi** [comment]
An idea would be to also consider actual tracing with [Jaeger](https://github.com/jaegertracing/jaeger-client-go), but that's likely different to this issue.

**Comment by lippserd** [comment]
We moved to zap.
