### ISSUE TITLE
Error 1264: Out of range value for column 'argument_order' at row 163

### ISSUE THREAD

**Issue by marcelfischer** [Icinga/icingadb#139]
Hi,
I installed all the release candidate versions of icinga2, icingaweb2, icingadb ...
After starting icingadb, it crashes a few minutes later with a error messages similar to this:
FATA[0005] Error 1264: Out of range value for column 'argument_order' at row 148

The row number changes sometimes.

I changed the table like this and now its working:
ALTER TABLE checkcommand_argument MODIFY argument_order INTEGER;

**Comment by N-o-X** [comment]
Hey @marcelfischer,
that's indeed a problem, if you have commands with 128+ arguments.

Thanks for reporting!
