### ISSUE TITLE
go mod update & dependabot

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icingadb#141]
I'd suggest the following changes:

* Update go modules `go get -u ./...`
* Enable dependabot for the repository (does automatic PRs): https://dependabot.com/go/

For an example, see https://github.com/NETWAYS/check_hp_disk_firmware and [pull requests](https://github.com/NETWAYS/check_hp_disk_firmware/pulls?q=is%3Apr+bump)

It helps to first update manually, or dependabot will open a bunch of PRs

**Comment by N-o-X** [comment]
I've added dependabot. Thanks for the suggestion! 👍
