### ISSUE TITLE
Add scheduling_source to state and history

### ISSUE THREAD

**Issue by N-o-X** [Icinga/icingadb#160]
refs https://github.com/Icinga/icinga2/pull/6326

**Comment by Al2Klimov** [comment]
I'm afraid due to https://github.com/Icinga/icinga2/pull/6326#event-4819652171 ...

**Comment by nilmerg** [comment]
Because there's only a documentation update missing that we could also do?

I mean, that's a schema change. We shouldn't require schema changes after RC2, as we want to proceed quickly to 1.0 stable without extensive changes, I guess.

**Comment by julianbrost** [comment]
> I'm afraid due to [Icinga/icinga2#6326 (comment)](https://github.com/Icinga/icinga2/pull/6326#event-4819652171) ...

My reason for moving it back then was that it's an external contribution that still needs changes and didn't look to me like this will happen soon. If you think this is important for Icinga DB, you could also add the required changes and we can probably still get this into 2.13.0

**Comment by Al2Klimov** [comment]
> We shouldn't require schema changes after RC2

C'mon. Have a look at the IDO. 😃
