### ISSUE TITLE
documentation : mysql -u root icingadb -p 

### ISSUE THREAD

**Issue by fabricelaborie** [Icinga/icingadb#169]
in https://icinga.com/docs/icingadb/latest/doc/02-Installation/
in the section  Setting up the MySQL database

cat /usr/share/icingadb/schema/mysql/mysql.schema.sql | mysql -uroot icingadb 
should  probably be
cat /usr/share/icingadb/schema/mysql/mysql.schema.sql | mysql -uroot icingadb -p

**Comment by Al2Klimov** [comment]
`-p`'s already there.
