### ISSUE TITLE
Redis + TLS

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingadb#188]
Redis v6.0.x is out and provides TLS support.

**Comment by Al2Klimov** [comment]
@N-o-X Shall we require TLS?

**Comment by N-o-X** [comment]
We should definitely look into that for the 1.0 release. 

Thoughts (to discuss after Icinga 2.12 release):

- go-redis library compatible?
- Need to update our Redis packages
- TLS as a requirement or optional?

We'll talk about this after 2.12.

**Comment by Al2Klimov** [comment]
1. Compatible.
2. Of course.
3. The cluster traffic is force-TLSed, too after all.

**Comment by Al2Klimov** [comment]
Hm... *after* v2.12? Can we force TLS **after** v2.12?

**Comment by N-o-X** [comment]
Maybe we should not force this at all. Adding TLS to 2.12 would delay that version a lot and adding it later with a 2.12.x shouldn't be a problem.
