### ISSUE TITLE
Not recovering overdue checks

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb#197]
I sometimes have the issue that my system can't keep up with the check frequency Icinga 2 schedules checks with. That's especially apparent when I launch my dev-environment in the morning. The result are many checks that are overdue.

This however is not the real problem, it's only what triggers it. It's actually the fact, that overdue indicators are not cleared until a check switches its hard state. Since most of my checks are synthetic ones, they won't change their state often or even not at all. So they're indeed checked in time after a while and are actually not overdue anymore, though Icinga DB will still report them as such.

While my environment clearly provokes this issue, I can imagine this being a real-world issue as well. Especially some agents may also often process checks later/longer than usual but won't report many state changes.

**Comment by mikeb93** [comment]
I've recently installed a fresh Server for a customer and encountered this issue.
Traditional monitoring module works fine, icingadb shows overdue checks (always around 2 min late, never really changes).

If I can help with any log files please let me know

**Comment by julianbrost** [comment]
At the moment, I know two situations in which checks can remain overdue:
1. Redis data is not persisted
2. Running a HA setup with two Icinga DB instances

@mikeb93 Does at least one of these two apply to your setup? Or may there be yet another issue?
