### ISSUE TITLE
icingadb service failed to start

### ISSUE THREAD

**Issue by usmanC9** [Icinga/icingadb#199]
Icingadb service failed to start with the following message.
 
INFO[0000] Connecting to Redis
INFO[0000] Connecting to MySQL
INFO[0000] Redis connection established
INFO[0000] Starting heartbeat listener
INFO[0000] SQL connection established
INFO[0000] Got initial environment.                      UUID=376f3ccf-b1dc-43d8-901b-eb7baf310df7 context=HA environment=da39a3ee5e6b4b0d3255bfef95601890afd80709
INFO[0000] Taking over.                                  UUID=376f3ccf-b1dc-43d8-901b-eb7baf310df7 context=HA environment=da39a3ee5e6b4b0d3255bfef95601890afd80709
INFO[0001] Inserted 3 customvar_flats in 19.813759ms     action=insert benchmark=19.813759ms count=3 type=customvar_flat
INFO[0001] Inserted 438 service_states in 80.771623ms    action=insert benchmark=80.771623ms count=438 type=service_state
FATA[0001] Error 1406: Data too long for column 'performance_data' at row 106

**icinga2 version**
icinga2 - The Icinga 2 network monitoring daemon (version: 2.12.0-0.rc1.1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-957.10.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-LTrJQZ9N-project-322-concurrent-0
  OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

**icingadb version**
Icinga DB version: v1.0.0-rc1

**Comment by Al2Klimov** [comment]
## Task

Explain in your own words what’s the problem.

**Comment by Yonas-net** [comment]
It looks like ``IcingaDB`` is writing data that does not match the size of a Mysql ``text`` data type.

**Comment by Al2Klimov** [comment]
1. Which column?
2. What's the size?

**Comment by Yonas-net** [comment]
> Which column?

``performance_data``.

> What's the size?

min. ``256 bytes`` & max. ``4GB``

**Comment by Al2Klimov** [comment]
> min. `256 bytes` & max. `4GB`

Strange, where did you get such info?

**Comment by Yonas-net** [comment]
https://dev.mysql.com/doc/refman/8.0/en/storage-requirements.html

**Comment by Al2Klimov** [comment]
Actually [the column](https://github.com/Icinga/icingadb/blob/88deca05b73f95f86f1bc91fd1bb83ed42494be6/etc/schema/mysql/mysql.schema.sql#L280) is of type TEXT and allows up to 64KB. There are also MEDIUMTEXT (16MB) and LONGTEXT (4GB). Have a look at the whole schema and summarize which TEXT columns would you make MEDIUMTEXT/LONGTEXT and why.

**Comment by Yonas-net** [comment]
So, for most columns which have text as data type, you could replace with ``MEDIUMTEXT``, because there won't be e.g. 4GB big PerfData for a single host/service object. And for the ``long_output`` column, it would be appropriate if it would have ``LONGTEXT`` as data type because as the column name also obviously points out, it is a long output and could perhaps be 4GB in size.

**Comment by Al2Klimov** [comment]
I'd only extend output, long_output and performance_data to MEDIUMTEXT, and not the others – not even comment. @lippserd Any objections?

**Comment by lippserd** [comment]
> I'd only extend output, long_output and performance_data to MEDIUMTEXT, and not the others – not even comment. @lippserd Any objections?

No objections. @raviks789 truncate code should still be considered. If we have data > 16 MB, Icinga DB still crashes again..
