### ISSUE TITLE
IcingaDB Service fails...

### ISSUE THREAD

**Issue by ChristianMoritz** [Icinga/icingadb#202]
The Connect from the Icinga Director Database Source through the icingadb in mysql works.
the redis-core works aswell

And on the WEB Gui, ill get the following error:
_**It seems that Icinga DB is not running. Make sure Icinga DB is running and writing into the database.**_

(icngadb feature is enabled, and on the module config, the mysql db and the redis server (127.0.0.1) are set properly.

**Installed Apps:**
redis-cli v4.0.9
icingadb, icingadb-redis

**Config from Redis**
```
root@smon03:/# redis-cli info server
# Server
redis_version:4.0.9
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:9435c3c2879311f3
redis_mode:standalone
os:Linux 4.15.0-108-generic x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:7.4.0
process_id:822
run_id:1fa9f21dd5fb9b544b3aed7d4f18fa84e1d2224f
tcp_port:6379
uptime_in_seconds:65901
uptime_in_days:0
hz:10
lru_clock:16531508
executable:/usr/bin/redis-server
config_file:/etc/redis/redis.conf
```

**Config from icingadb.ini**
root@smon03:/# cat /etc/icingadb/icingadb.ini
```
[redis]
host="127.0.0.1"
port=6380

[mysql]
host="127.0.0.1"
port="3306"
database="icingadb"
user="icingadb"
password="MySuperSecretPW"

[logging]
level="info"
```

**Error Log (Info Level)**
```
root@smon03:/# service icingadb status
● icingadb.service - Icinga DB
   Loaded: loaded (/lib/systemd/system/icingadb.service; disabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-07-01 09:32:53 CEST; 4min 51s ago
 Main PID: 2577 (icingadb)
    Tasks: 13 (limit: 4915)
   CGroup: /system.slice/icingadb.service
           └─2577 /usr/sbin/icingadb --config /etc/icingadb/icingadb.ini

Jul 01 09:32:53 smon03 systemd[1]: Started Icinga DB.
Jul 01 09:32:53 smon03 icingadb[2577]: time="2020-07-01T09:32:53+02:00" level=info msg="Connecting to Redis"
Jul 01 09:32:53 smon03 icingadb[2577]: time="2020-07-01T09:32:53+02:00" level=error msg="Could not connect to Redis. Trying again" context=redis error="dial tcp 127.0.0.1:6380: connect: connection refused"
Jul 01 09:32:53 smon03 icingadb[2577]: time="2020-07-01T09:32:53+02:00" level=info msg="Connecting to MySQL"
Jul 01 09:32:53 smon03 icingadb[2577]: time="2020-07-01T09:32:53+02:00" level=error msg="Could not connect to SQL. Trying again" context=sql error="dial tcp 127.0.0.1:3306: connect: connection refused"
Jul 01 09:32:53 smon03 icingadb[2577]: time="2020-07-01T09:32:53+02:00" level=info msg="Starting heartbeat listener"
```

**Error Log (debug level)**
```

root@smon03:/# icingadb -config /etc/icingadb/icingadb.ini
INFO[0000] Connecting to Redis
ERRO[0000] Could not connect to Redis. Trying again      context=redis error="dial tcp 127.0.0.1:6380: connect: connection refused"
INFO[0000] Connecting to MySQL
ERRO[0000] Could not connect to SQL. Trying again        context=sql error="dial tcp 127.0.0.1:3306: connect: connection refused"
DEBU[0000] SQL connection lost. Trying again in 5s       context=sql error="dial tcp 127.0.0.1:3306: connect: connection refused"
DEBU[0000] timeperiod_override_include: Ready
DEBU[0000] timeperiod_override_exclude: Ready
DEBU[0000] zone: Ready
DEBU[0000] usernotificationHistory: Waiting for EnvId to be set
DEBU[0000] downtimeHistory: Waiting for EnvId to be set
DEBU[0000] notificationHistory: Waiting for EnvId to be set
INFO[0000] Starting heartbeat listener
DEBU[0000] commentHistory: Waiting for EnvId to be set
DEBU[0000] endpoint: Ready
DEBU[0000] checkcommand_customvar: Ready
DEBU[0000] checkcommand_argument: Ready
DEBU[0000] checkcommand_envvar: Ready
DEBU[0000] eventcommand: Ready
DEBU[0000] eventcommand_customvar: Ready
DEBU[0000] eventcommand_argument: Ready
DEBU[0000] eventcommand_envvar: Ready
DEBU[0000] notificationcommand: Ready
DEBU[0000] notificationcommand_customvar: Ready
DEBU[0000] notificationcommand_argument: Ready
DEBU[0000] notificationcommand_envvar: Ready
DEBU[0000] comment: Ready
DEBU[0000] host_state: Ready
DEBU[0000] OverdueSync: Waiting for EnvId to be set
DEBU[0000] OverdueSync: Waiting for EnvId to be set
DEBU[0000] Redis connection lost. Trying again in 5s     context=redis error="dial tcp 127.0.0.1:6380: connect: connection refused"
DEBU[0000] stateHistory: Waiting for EnvId to be set
DEBU[0000] flappingHistory: Waiting for EnvId to be set
DEBU[0000] acknowledgementHistory: Waiting for EnvId to be set
DEBU[0000] StateSync: Waiting for EnvId to be set
DEBU[0000] StateSync: Waiting for EnvId to be set
DEBU[0000] usergroup_member: Ready
DEBU[0000] notification: Ready
DEBU[0000] host: Ready
DEBU[0000] notification_customvar: Ready
DEBU[0000] notification_user: Ready
DEBU[0000] host_customvar: Ready
DEBU[0000] servicegroup: Ready
DEBU[0000] icon_image: Ready
DEBU[0000] servicegroup_customvar: Ready
DEBU[0000] servicegroup_member: Ready
DEBU[0000] notification_usergroup: Ready
DEBU[0000] user: Ready
DEBU[0000] notification_recipient: Ready
DEBU[0000] user_customvar: Ready
DEBU[0000] customvar: Ready
DEBU[0000] usergroup: Ready
DEBU[0000] usergroup_customvar: Ready
DEBU[0000] customvar_flat: Ready
DEBU[0000] timeperiod: Ready
DEBU[0000] action_url: Ready
DEBU[0000] notes_url: Ready
DEBU[0000] downtime: Ready
DEBU[0000] service: Ready
DEBU[0000] service_customvar: Ready
DEBU[0000] timeperiod_range: Ready
DEBU[0000] service_state: Ready
DEBU[0000] hostgroup: Ready
DEBU[0000] hostgroup_customvar: Ready
DEBU[0000] hostgroup_member: Ready
DEBU[0000] timeperiod_customvar: Ready
DEBU[0000] checkcommand: Ready
DEBU[0001] usernotificationHistory: Waiting for EnvId to be set
DEBU[0001] downtimeHistory: Waiting for EnvId to be set
DEBU[0001] notificationHistory: Waiting for EnvId to be set
DEBU[0001] commentHistory: Waiting for EnvId to be set
DEBU[0001] OverdueSync: Waiting for EnvId to be set
DEBU[0001] OverdueSync: Waiting for EnvId to be set
DEBU[0001] stateHistory: Waiting for EnvId to be set
DEBU[0001] flappingHistory: Waiting for EnvId to be set
DEBU[0001] acknowledgementHistory: Waiting for EnvId to be set
DEBU[0001] StateSync: Waiting for EnvId to be set
DEBU[0001] StateSync: Waiting for EnvId to be set
DEBU[0002] usernotificationHistory: Waiting for EnvId to be set
DEBU[0002] downtimeHistory: Waiting for EnvId to be set
DEBU[0002] notificationHistory: Waiting for EnvId to be set
DEBU[0002] commentHistory: Waiting for EnvId to be set
DEBU[0002] OverdueSync: Waiting for EnvId to be set
DEBU[0002] OverdueSync: Waiting for EnvId to be set
DEBU[0002] stateHistory: Waiting for EnvId to be set
DEBU[0002] flappingHistory: Waiting for EnvId to be set
DEBU[0002] acknowledgementHistory: Waiting for EnvId to be set
DEBU[0002] StateSync: Waiting for EnvId to be set
DEBU[0002] StateSync: Waiting for EnvId to be set
DEBU[0003] usernotificationHistory: Waiting for EnvId to be set
DEBU[0003] downtimeHistory: Waiting for EnvId to be set
DEBU[0003] notificationHistory: Waiting for EnvId to be set
DEBU[0003] commentHistory: Waiting for EnvId to be set
DEBU[0003] OverdueSync: Waiting for EnvId to be set
DEBU[0003] OverdueSync: Waiting for EnvId to be set
DEBU[0003] stateHistory: Waiting for EnvId to be set
DEBU[0003] flappingHistory: Waiting for EnvId to be set
DEBU[0003] acknowledgementHistory: Waiting for EnvId to be set
DEBU[0003] StateSync: Waiting for EnvId to be set
DEBU[0003] StateSync: Waiting for EnvId to be set
DEBU[0004] usernotificationHistory: Waiting for EnvId to be set
DEBU[0004] downtimeHistory: Waiting for EnvId to be set
DEBU[0004] notificationHistory: Waiting for EnvId to be set
DEBU[0004] commentHistory: Waiting for EnvId to be set
DEBU[0004] OverdueSync: Waiting for EnvId to be set
DEBU[0004] OverdueSync: Waiting for EnvId to be set
DEBU[0004] stateHistory: Waiting for EnvId to be set
DEBU[0004] flappingHistory: Waiting for EnvId to be set
DEBU[0004] acknowledgementHistory: Waiting for EnvId to be set
DEBU[0004] StateSync: Waiting for EnvId to be set
DEBU[0004] StateSync: Waiting for EnvId to be set
DEBU[0005] SQL connection lost. Trying again in 5s       context=sql error="dial tcp 127.0.0.1:3306: connect: connection refused"
DEBU[0005] usernotificationHistory: Waiting for EnvId to be set
DEBU[0005] downtimeHistory: Waiting for EnvId to be set
DEBU[0005] notificationHistory: Waiting for EnvId to be set
DEBU[0005] commentHistory: Waiting for EnvId to be set
DEBU[0005] OverdueSync: Waiting for EnvId to be set
DEBU[0005] Redis connection lost. Trying again in 5s     context=redis error="dial tcp 127.0.0.1:6380: connect: connection refused"
DEBU[0005] OverdueSync: Waiting for EnvId to be set
DEBU[0005] stateHistory: Waiting for EnvId to be set
DEBU[0005] flappingHistory: Waiting for EnvId to be set
DEBU[0005] acknowledgementHistory: Waiting for EnvId to be set
DEBU[0005] StateSync: Waiting for EnvId to be set
DEBU[0005] StateSync: Waiting for EnvId to be set
DEBU[0006] usernotificationHistory: Waiting for EnvId to be set
DEBU[0006] downtimeHistory: Waiting for EnvId to be set
DEBU[0006] notificationHistory: Waiting for EnvId to be set
DEBU[0006] commentHistory: Waiting for EnvId to be set
DEBU[0006] OverdueSync: Waiting for EnvId to be set
DEBU[0006] OverdueSync: Waiting for EnvId to be set
DEBU[0006] stateHistory: Waiting for EnvId to be set
DEBU[0006] flappingHistory: Waiting for EnvId to be set
DEBU[0006] acknowledgementHistory: Waiting for EnvId to be set
DEBU[0006] StateSync: Waiting for EnvId to be set
DEBU[0006] StateSync: Waiting for EnvId to be set
^CINFO[0006] Shutting down 
```

**My Icinga2 enviroment:**
```
root@smon03:/# icingacli --version
Icinga Web 2  2.8.0-rc1
Git Commit    95328553ca1336701044282c3b065a20f36af039
PHP Version   7.2.24-0ubuntu0.18.04.6
MODULE         VERSION
director       1.7.2
icingadb       1.0.0-rc1
idoreports     0.9.1
incubator      0.5.0
ipl            v0.5.0
monitoring     2.8.0-rc1
reactbundle    0.7.0
```

**Comment by N-o-X** [comment]
Hi @ChristianMoritz, sorry for the late reply. 

I can see a few issues with your setup:
- Your Redis is listening on port 6379, but Icinga DB tries to connect on port 6380.
- Your Redis instance is on version 4.x, but Icinga DB needs at least 5.x.
- From the Icinga DB logs it's clear that something is wrong with your connection to the SQL server. Are you sure you used the right host and credentials?
- Is there a Icinga 2.12 instance writing to the Redis instance?

The message `It seems that Icinga DB is not running. Make sure Icinga DB is running and writing into the database.` will only go away if:
- Icinga 2 writes to Redis
- Icinga DB can connect to Redis and MySQL

Greetings
Noah

**Comment by ChristianMoritz** [comment]
Hy NOX,

after i cange the REDIS port the 1 error is gone...

all features run on the same MASTER (Icinga2, SQL & Redis)

when i login to the sql with the user i can see the database is there...
root@smon03:/# mysql -u icingadb -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 443359
Server version: 5.7.30-0ubuntu0.18.04.1 (Ubuntu)

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| icingadb           |
+--------------------+
2 rows in set (0.00 sec)
mysql>

but from the app im still unable to get the SQL connect...
root@smon03:/# icingadb -config /etc/icingadb/icingadb.ini
INFO[0000] Connecting to Redis
INFO[0000] Connecting to MySQL
ERRO[0000] Could not connect to SQL. Trying again        context=sql error="dial tcp 127.0.0.1:3306: connect: connection refused"
INFO[0000] Redis connection established
INFO[0000] Starting heartbeat listener
FATA[0000] ERR unknown command 'xread'

and if i test teh sql connect with the sql root user i got the same error....

**Comment by N-o-X** [comment]
Hi,

you still need to upgrade Redis to 5.x: `FATA[0000] ERR unknown command 'xread'`. I would suggest using the `icinga-redis` package from our [official repositories](http://packages.icinga.com/ubuntu/). This will install a separate service(`icinga-redis`) from your default Redis installation and run on port 6380.

There must be something wrong with your SQL setup. You could try using the unix socket by connection via `localhost` instead of `127.0.0.1`.

Greetings
Noah

**Comment by ChristianMoritz** [comment]
okay... ive uninstalled the packages and installed the new ones...

on the web gui the connect to redis & sql db is OK.
![image](https://user-images.githubusercontent.com/36260833/88639597-3bdda800-d0bd-11ea-949f-c8aefdcefddf.png)

only on the CLI i've got the problem with the SQL connect (im using the same logins for GUI and CLI)
root@smon03:/# cat /etc/icingadb/icingadb.ini
[redis]
host="127.0.0.1"
port=6379

[mysql]
host="127.0.0.1"
port="3306"
database="icingadb"
user="root"
password="MySecretPW"

[logging]
level="info"

[metrics]
#host="127.0.0.1"
#port=8080
root@smon03:/#


**the config call**
root@smon03:/# icingadb -config /etc/icingadb/icingadb.ini
INFO[0000] Connecting to Redis
INFO[0000] Connecting to MySQL
ERRO[0000] Could not connect to SQL. Trying again        context=sql error="dial tcp 127.0.0.1:3306: connect: connection refused"
INFO[0000] Starting heartbeat listener
INFO[0000] Redis connection established
FATA[0000] ERR unknown command 'xread'

**installed modules are now:**
icinga-redis/icinga-bionic,now 5.0.7-4.bionic amd64 [installed]
icingadb-redis/icinga-bionic-testing,now 1.0.0~rc1-2.bionic amd64 [installed]
redis/bionic-updates,bionic-updates,bionic-security,bionic-security,now 5:4.0.9-1ubuntu0.2 all [installed]
redis-server/bionic-updates,bionic-security,now 5:4.0.9-1ubuntu0.2 amd64 [installed]


**and this is the redis-server version**
root@smon03:/# redis-server --version
Redis server v=4.0.9 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=9435c3c2879311f3


and i cant find a service called icinga-redis
root@smon03:/# systemctl icinga-redis status
Unknown operation icinga-redis.

so clould it be that the service for the icinga-redis wouldnd be installed properly ?

**Comment by N-o-X** [comment]
You're still using the old Redis server in your Icinga DB config. Please change the Redis port to 6380, as I said in my last comment. Also, please try to use `localhost` as the SQL host in your Icinga DB config.

You're right, I forgot something. You also need to install the `icingadb-redis` package, which includes the service file.
But your usage of the `systemctl` command is also wrong. It should be `systemctl status icingadb-redis`, so you mixed up the operation and the service name.

The `redis-server` command has been renamed to `icinga-redis-server` in our packages. So you should use that to get the version.

**Comment by ChristianMoritz** [comment]
okay,

now ive changed the redis to the icinga-redis...

root@smon03:/# icinga-redis-server --version
Redis server v=5.0.7 sha=7566f0e4:0 malloc=jemalloc-3.6.0 bits=64 build=2ff796ab36146db6

but ive got still the sql connection problem.

**with "localhost"**
root@smon03:/# sudo icingadb -config /etc/icingadb/icingadb.ini
INFO[0000] Connecting to Redis
INFO[0000] Connecting to MySQL
ERRO[0000] Could not connect to SQL. Trying again        context=sql error="dial tcp [::1]:3306: connect: connection refused"
INFO[0000] Redis connection established
INFO[0000] Starting heartbeat listener
^CINFO[0003] Shutting down  

**with "127.0.0.1"**

**and with the real host ip**
root@smon03:/# sudo icingadb -config /etc/icingadb/icingadb.ini
INFO[0000] Connecting to Redis
INFO[0000] Connecting to MySQL
INFO[0000] Redis connection established
ERRO[0000] Could not connect to SQL. Trying again        context=sql error="Error 1045: Access denied for user 'root'@'10.10.10.24' (using password: YES)"
INFO[0000] Starting heartbeat listener
^CINFO[0002] Shutting down                                 signal=interrupt
root@smon03:/#


from the WEB GUI the connect only works with localhost, not with 127.0.0.1 or the real IP...
but the entry localhost in the config doesnt works.

so the problem for this was the bind-adress on the sql.cnf

after changing the binding to:
bind-address            = ::
and restarting the SQL service it works, but ive got a new error...
root@smon03:/etc/mysql/mysql.conf.d# sudo icingadb -config /etc/icingadb/icingadb.ini
INFO[0000] Connecting to Redis
INFO[0000] Connecting to MySQL
INFO[0000] Redis connection established
INFO[0000] Starting heartbeat listener
INFO[0000] SQL connection established
INFO[0000] Got initial environment.                      UUID=b6a94241-a8a8-4ea5-a3d9-9e32c87d172f context=HA environment=da39a3ee5e6b4b0d3255bfef95601890afd80709
INFO[0000] Taking over.                                  UUID=b6a94241-a8a8-4ea5-a3d9-9e32c87d172f context=HA environment=da39a3ee5e6b4b0d3255bfef95601890afd80709
INFO[0001] Inserted 274 checkcommands in 97.809396ms     action=insert benchmark=97.809396ms count=274 type=checkcommand
INFO[0001] Inserted 193 endpoints in 131.277483ms        action=insert benchmark=131.277483ms count=193 type=endpoint
INFO[0001] Inserted 1265 checkcommand_customvars in 136.929337ms  action=insert benchmark=136.929337ms count=1265 type=checkcommand_customvar
INFO[0001] Inserted 5 checkcommand_envvars in 96.638386ms  action=insert benchmark=96.638386ms count=5 type=checkcommand_envvar
INFO[0001] Inserted 5 timeperiods in 38.605402ms         action=insert benchmark=38.605402ms count=5 type=timeperiod
INFO[0001] Inserted 26 timeperiod_ranges in 17.311952ms  action=insert benchmark=17.311952ms count=26 type=timeperiod_range
INFO[0001] Inserted 3155 checkcommand_arguments in 282.795320ms  action=insert benchmark=282.795320ms count=3155 type=checkcommand_argument
INFO[0001] Inserted 5 servicegroups in 163.795919ms      action=insert benchmark=163.795919ms count=5 type=servicegroup
INFO[0001] Inserted 8 notificationcommands in 122.224943ms  action=insert benchmark=122.224943ms count=8 type=notificationcommand
INFO[0001] Inserted 4 usergroups in 158.946935ms         action=insert benchmark=158.946935ms count=4 type=usergroup
INFO[0001] Inserted 92 notificationcommand_arguments in 12.868919ms  action=insert benchmark=12.868919ms count=92 type=notificationcommand_argument
INFO[0001] Inserted 33 notificationcommand_customvars in 109.705255ms  action=insert benchmark=109.705255ms count=33 type=notificationcommand_customvar
INFO[0001] Inserted 195 zones in 304.017964ms            action=insert benchmark=304.017964ms count=195 type=zone
INFO[0001] Inserted 8 comments in 92.443030ms            action=insert benchmark=92.443030ms count=8 type=comment
INFO[0001] Inserted 1491 servicegroup_members in 596.895668ms  action=insert benchmark=596.895668ms count=1491 type=servicegroup_member
INFO[0002] Inserted 16 hostgroups in 26.703218ms         action=insert benchmark=26.703218ms count=16 type=hostgroup
INFO[0002] Inserted 316 hostgroup_members in 345.144767ms  action=insert benchmark=345.144767ms count=316 type=hostgroup_member
INFO[0002] Inserted 1466 host_customvars in 411.998357ms  action=insert benchmark=411.998357ms count=1466 type=host_customvar
INFO[0002] Inserted 3424 service_states in 1.441234s     action=insert benchmark=1.441234s count=3424 type=service_state
INFO[0002] Inserted 4 downtimes in 531.311688ms          action=insert benchmark=531.311688ms count=4 type=downtime
INFO[0002] Inserted 9430 service_customvars in 1.497283s  action=insert benchmark=1.497283s count=9430 type=service_customvar
INFO[0002] Inserted 4 users in 194.793670ms              action=insert benchmark=194.793670ms count=4 type=user
**FATA[0002] Error 1265: Data truncated for column 'notifications_enabled' at row 4**
root@smon03:/etc/mysql/mysql.conf.d#


the truncated error also appears if i re run the script.
root@smon03:/etc/mysql/mysql.conf.d# sudo icingadb -config /etc/icingadb/icingadb.ini
INFO[0000] Connecting to Redis
INFO[0000] Connecting to MySQL
INFO[0000] Redis connection established
INFO[0000] Starting heartbeat listener
INFO[0000] SQL connection established
INFO[0000] Got initial environment.                      UUID=ae4eb315-f0f2-4c68-bd25-a549ef736329 context=HA environment=da39a3ee5e6b4b0d3255bfef95601890afd80709
INFO[0000] Other instance is active.                     UUID=ae4eb315-f0f2-4c68-bd25-a549ef736329 context=HA environment=da39a3ee5e6b4b0d3255bfef95601890afd80709
INFO[0013] Taking over.                                  UUID=ae4eb315-f0f2-4c68-bd25-a549ef736329 context=HA environment=da39a3ee5e6b4b0d3255bfef95601890afd80709
**FATA[0014] Error 1265: Data truncated for column 'notifications_enabled' at row 4**
root@smon03:/etc/mysql/mysql.conf.d#

is there anything else wrong or is this error "made by design ??"

**Comment by ChristianMoritz** [comment]
i found the sollution for this error here..
https://github.com/Icinga/icingadb/issues/176

ive cleaned up the notify policy's... not it seems to work.

**Comment by ChristianMoritz** [comment]
works after changing the config and cleaning up the notifiy options.... (thanks N-O-X) (y)
