### ISSUE TITLE
Missing instructions on how to enable Icinga 2's icingadb feature

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb#206]
The [installation documentation of Icinga DB](https://icinga.com/docs/icingadb/latest/doc/02-Installation/) doesn't include any hint that the icingadb feature of Icinga 2 is necessary to complete the installation.

This is only covered in [Icinga 2's documentation.](https://icinga.com/docs/icinga2/latest/doc/02-installation/#icinga-db) The Icinga DB documentation should at least provide a link to that.

Otherwise many users won't know that enabling the feature is a required step for a functional Icinga DB environment.

**Comment by lippserd** [comment]
Will be fixed w/ #159.
