### ISSUE TITLE
can we get another RC with the latest fixes?

### ISSUE THREAD

**Issue by lesinigo** [Icinga/icingadb#216]
Hi guys, while researching some MySQL connection issues we saw they were fixed in #146 and that there are many other issues already fixed in code since the last tagged release.

Is it possible to get another rc release tagged and packaged in DEB/RPM with all the latest fixes? it would make testing icingadb much easier for us out there without an established build pipeline.

thank you!

**Comment by N-o-X** [comment]
Hi @lesinigo,

if you just want to test the latest changes, you can just use our snapshot repository instead of using testing.

Greetings
Noah

**Comment by lesinigo** [comment]
@N-o-X exactly, I would like to test the latest changes, but if you mean this repo ( https://packages.icinga.com/epel/7/snapshot/x86_64/icingadb/ ) the latest rpm I see is from april 2020 and I count around 8 closed issues since then.

In our testing we get frequent IcingaDB crashes and they could be related to #146 or other PRs merged after the latest RPM and we'd like to test against the latest and greatest, but right now it wouldn't be easy for us to build our own packages.

**Comment by N-o-X** [comment]
@lesinigo sorry for answering that late. 
The latest snapshots are now also available on CentOS/RHEL 7. Hope that helps you going forward.

Thanks for testing! 🚀
