### ISSUE TITLE
enum('y', 'n') in database schema has counterintuitive sort order

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icingadb#234]
I suggest to replace `enum('y', 'n')` in the database schema with `enum('n', 'y')` to get a more natural sort order.

Enums are sorted in the order they are given in the type, i.e. currently 'y' < 'n', which is different from both the alphabetical order and when representing false/true as 0/1.

https://dev.mysql.com/doc/refman/8.0/en/enum.html#enum-sorting
https://www.postgresql.org/docs/13/datatype-enum.html#id-1.5.7.15.6

**Comment by Al2Klimov** [comment]
Did we agree on anything regarding yes/no/sticky?
