### ISSUE TITLE
"$type: Waiting for EnvId to be set" messages pollute the debug log

### ISSUE THREAD

**Issue by lippserd** [Icinga/icingadb#254]
When Icinga DB waits for the `EnvId` it logs the `"$type: Waiting for EnvId to be set"` message every second for every type. I expect to see this only once.

> DEBU[0532] OverdueSync: Waiting for EnvId to be set
DEBU[0532] usernotificationHistory: Waiting for EnvId to be set
DEBU[0532] commentHistory: Waiting for EnvId to be set
DEBU[0532] OverdueSync: Waiting for EnvId to be set
DEBU[0532] StateSync: Waiting for EnvId to be set
DEBU[0532] stateHistory: Waiting for EnvId to be set
DEBU[0532] notificationHistory: Waiting for EnvId to be set
DEBU[0532] acknowledgementHistory: Waiting for EnvId to be set
DEBU[0532] flappingHistory: Waiting for EnvId to be set
DEBU[0532] StateSync: Waiting for EnvId to be set
DEBU[0532] downtimeHistory: Waiting for EnvId to be set
DEBU[0533] downtimeHistory: Waiting for EnvId to be set
DEBU[0533] notificationHistory: Waiting for EnvId to be set
DEBU[0533] commentHistory: Waiting for EnvId to be set
DEBU[0533] OverdueSync: Waiting for EnvId to be set
DEBU[0533] usernotificationHistory: Waiting for EnvId to be set
DEBU[0533] acknowledgementHistory: Waiting for EnvId to be set
DEBU[0533] OverdueSync: Waiting for EnvId to be set
DEBU[0533] stateHistory: Waiting for EnvId to be set
DEBU[0533] flappingHistory: Waiting for EnvId to be set
DEBU[0533] StateSync: Waiting for EnvId to be set
DEBU[0533] StateSync: Waiting for EnvId to be set
DEBU[0534] StateSync: Waiting for EnvId to be set
DEBU[0534] flappingHistory: Waiting for EnvId to be set
DEBU[0534] usernotificationHistory: Waiting for EnvId to be set
DEBU[0534] notificationHistory: Waiting for EnvId to be set
DEBU[0534] downtimeHistory: Waiting for EnvId to be set
DEBU[0534] stateHistory: Waiting for EnvId to be set
DEBU[0534] OverdueSync: Waiting for EnvId to be set
DEBU[0534] OverdueSync: Waiting for EnvId to be set
DEBU[0534] acknowledgementHistory: Waiting for EnvId to be set
DEBU[0534] StateSync: Waiting for EnvId to be set
DEBU[0534] commentHistory: Waiting for EnvId to be set
DEBU[0535] OverdueSync: Waiting for EnvId to be set
DEBU[0535] stateHistory: Waiting for EnvId to be set
DEBU[0535] notificationHistory: Waiting for EnvId to be set
DEBU[0535] downtimeHistory: Waiting for EnvId to be set
DEBU[0535] acknowledgementHistory: Waiting for EnvId to be set
DEBU[0535] StateSync: Waiting for EnvId to be set
DEBU[0535] usernotificationHistory: Waiting for EnvId to be set
DEBU[0535] commentHistory: Waiting for EnvId to be set
DEBU[0535] OverdueSync: Waiting for EnvId to be set
DEBU[0535] StateSync: Waiting for EnvId to be set
DEBU[0535] flappingHistory: Waiting for EnvId to be set
DEBU[0536] acknowledgementHistory: Waiting for EnvId to be set
DEBU[0536] notificationHistory: Waiting for EnvId to be set
DEBU[0536] flappingHistory: Waiting for EnvId to be set
DEBU[0536] StateSync: Waiting for EnvId to be set
DEBU[0536] usernotificationHistory: Waiting for EnvId to be set
DEBU[0536] commentHistory: Waiting for EnvId to be set
DEBU[0536] OverdueSync: Waiting for EnvId to be set
DEBU[0536] StateSync: Waiting for EnvId to be set
DEBU[0536] downtimeHistory: Waiting for EnvId to be set
DEBU[0536] OverdueSync: Waiting for EnvId to be set
DEBU[0536] stateHistory: Waiting for EnvId to be set
DEBU[0537] OverdueSync: Waiting for EnvId to be set
DEBU[0537] downtimeHistory: Waiting for EnvId to be set
DEBU[0537] stateHistory: Waiting for EnvId to be set
DEBU[0537] notificationHistory: Waiting for EnvId to be set
DEBU[0537] flappingHistory: Waiting for EnvId to be set
DEBU[0537] StateSync: Waiting for EnvId to be set
DEBU[0537] usernotificationHistory: Waiting for EnvId to be set
DEBU[0537] acknowledgementHistory: Waiting for EnvId to be set
DEBU[0537] commentHistory: Waiting for EnvId to be set
DEBU[0537] OverdueSync: Waiting for EnvId to be set

**Comment by Al2Klimov** [comment]
Once _per type_ or _at all_?

**Comment by lippserd** [comment]
Not a problem anymore as we've rewritten most of the code.
