### ISSUE TITLE
A downtime scheduled per API with `all_services` should be identifiable by the resulting service downtimes

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb#258]
i.e. a `scheduled_by_parent` column or so is required in the schema. Then DB Web can cancel all child downtimes if the parent host downtime is being cancelled.

**Comment by Al2Klimov** [comment]
Stupid question: shouldn’t the core do this by itself to save bandwidth?

**Comment by lippserd** [comment]
> Stupid question: shouldn’t the core do this by itself to save bandwidth?

That would be cool. Even so, we would have to identify / store relationships in the database to show this in the user interface.

**Comment by lippserd** [comment]
Closed via #323
