### ISSUE TITLE
Panic in configsync.(*ConfigSyncHA).runEventListener

### ISSUE THREAD

**Issue by dwt** [Icinga/icingadb#275]
While starting icingadb in a docker container it panics with this error message:

```log
panic: interface conversion: interface {} is nil, not string

goroutine 69 [running]:
github.com/Icinga/icingadb/configobject/configsync.(*ConfigSyncHA).runEventListener(0xc00022c400)
	/github/workspace/configobject/configsync/ha.go:96 +0x48e
github.com/Icinga/icingadb/configobject/configsync.(*ConfigSyncHA).run(0xc00022c400)
	/github/workspace/configobject/configsync/ha.go:51 +0x59
created by github.com/Icinga/icingadb/configobject/configsync.(*ConfigSyncHA).Start
	/github/workspace/configobject/configsync/ha.go:38 +0x3f
```

Icinga seems to run fine (its configuration validates and it sends me notifications) but of course the web interface is inaccessible / doesn't show any data without the icingadb syncing the data from redis. (By the way: is there a way to configure the web interface to talk to redis directly?)

I'm not good at reading Go code, but it seem that [this line](https://github.com/Icinga/icingadb/blob/d9e3c8b195ccacdca0d565239f035b3de9a381ea/configobject/configsync/ha.go#L96) either doesn't make amends for the value being null, or that icinga / redis on the other side doesn't provide that value correctly.

What do you guys think? Is there any workaround I can deploy in the meantime?

**Comment by dwt** [comment]
ping¿

**Comment by dwt** [comment]
Is there any additional data I can provide? Maybe some icinga config? (Not sure if that is relevant, given that this is an extra service that has hardly any config itself?)

Im running icingadb from the [official docker-container](https://github.com/Icinga/docker-icingadb). 

If there is any other info you guys need to debug this, please ask away.

**Comment by julianbrost** [comment]
We are currently preparing for a 1.0 RC2 with some bigger changes. This includes changes to the message formats in Redis, which are incompatible with the current Icinga DB snapshot builds. For now, I suggest to either downgrade the Icinga 2 snapshots, or wait until the required changes to Icinga DB also make it to the snapshot builds. I'll post an update here once this is possible.

**Comment by N-o-X** [comment]
We've just pushed our RC2 changes. Have a look at the [README](https://github.com/Icinga/icingadb#important-28052021) for information on upgrading if you want to test the newest version. Docker images and snapshot packages should be available in the next 1-2 days if that's something you need. Thanks for testing!
