### ISSUE TITLE
Column `last_comment_id` for hosts and services

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb#317]
Web would like to show the latest comment (no matter if ack or not) in the list. For this we need the `last_comment_id` in the `host` and `service` tables.

**Comment by Al2Klimov** [comment]
Is an index on `comment#host_id+service_id+entry_time` not an option?

**Comment by nilmerg** [comment]
Huh, no. A huge index for a single result at a time? Definitely no.

**Comment by Al2Klimov** [comment]
Sure, you'll use it _in the list_, but via subquery you could get _a single result_ **per row**.

**Comment by nilmerg** [comment]
I'll join the comments table based on the id by a left join. Not with a subquery..
