### ISSUE TITLE
Duplicate key errors after HA restart oder handover/takeover 

### ISSUE THREAD

**Issue by lippserd** [Icinga/icingadb#349]
Immediate takeovers after calling `cancelHaCtx` which happens after HA handovers or restart (#327) may result in duplicate key errors. This might happen for any type and is solely related to the config sync. To my knowledge, this does only happen if the config sync before calling `cancelHaCtx` did not finish. It seems that there can be multiple config syncs running at the same time.

**Comment by julianbrost** [comment]
Probably the same bug I observed in https://github.com/Icinga/icingadb/pull/336#issuecomment-896125651

**Comment by julianbrost** [comment]
> Probably the same bug I observed in [#336 (comment)](https://github.com/Icinga/icingadb/pull/336#issuecomment-896125651)

I'm no longer sure about this. At least I think the way I observed that bug can be triggered only due to an environment change, even though I'm not able to reliably reproduce this so far (see https://github.com/Icinga/icingadb/pull/336#issuecomment-908271242 for some more information on that).

So the one thing that I found that could be problematic even without an environment change and that could also explain

> It seems that there can be multiple config syncs running at the same time.

is that the HA takeover and subsequent context cancel may not propagate fast enough to actually tear down the old sync.

**Comment by julianbrost** [comment]
Regarding possible bugs in the sync implementation: do we properly handle that Redis `HSCAN` may return elements multiple times?

**Comment by julianbrost** [comment]
Wrong button...

**Comment by julianbrost** [comment]
> Regarding possible bugs in the sync implementation: do we properly handle that Redis `HSCAN` may return elements multiple times?

Well, that might either be it or another bug that results in the same symptom (as it has nothing to do with heartbeats).

Patching `HYield` so that it just returns every element twice (which is covered by the (H)SCAN consistency guarantees):
```diff
diff --git a/pkg/icingaredis/client.go b/pkg/icingaredis/client.go
index a56cb10..feeb385 100644
--- a/pkg/icingaredis/client.go
+++ b/pkg/icingaredis/client.go
@@ -104,14 +104,16 @@ func (c *Client) HYield(ctx context.Context, key string) (<-chan HPair, <-chan e
                        g.Go(func(page []string) func() error {
                                return func() error {
                                        for i := 0; i < len(page); i += 2 {
-                                               select {
-                                               case pairs <- HPair{
-                                                       Field: page[i],
-                                                       Value: page[i+1],
-                                               }:
-                                                       cnt.Inc()
-                                               case <-ctx.Done():
-                                                       return ctx.Err()
+                                               for j := 0; j < 2; j++ {
+                                                       select {
+                                                       case pairs <- HPair{
+                                                               Field: page[i],
+                                                               Value: page[i+1],
+                                                       }:
+                                                               cnt.Inc()
+                                                       case <-ctx.Done():
+                                                               return ctx.Err()
+                                                       }
                                                }
                                        }
 
```

This reliably gives duplicate key errors:
```
2021-08-31T16:29:28.524+0200	FATAL	icingadb/main.go:223	Error 1062: Duplicate entry '*T \xAE\x18W\xA9YS\xC9\xCDN\xC3\x9A\xF5\xCDH\xD4\xCE\x86' for key 'PRIMARY'
can't perform "INSERT INTO checkcommand_envvar (envvar_key, envvar_value, environment_id, properties_checksum, id, command_id) VALUES (:envvar_key, :envvar_value, :environment_id, :properties_checksum, :id, :command_id)"
github.com/icinga/icingadb/internal.CantPerformQuery
	/home/jbrost/dev/icingadb/internal/internal.go:30
github.com/icinga/icingadb/pkg/icingadb.(*DB).NamedBulkExec.func2.1.1.1
	/home/jbrost/dev/icingadb/pkg/icingadb/db.go:278
github.com/icinga/icingadb/pkg/retry.WithBackoff
	/home/jbrost/dev/icingadb/pkg/retry/retry.go:31
github.com/icinga/icingadb/pkg/icingadb.(*DB).NamedBulkExec.func2.1.1
	/home/jbrost/dev/icingadb/pkg/icingadb/db.go:272
golang.org/x/sync/errgroup.(*Group).Go.func1
	/home/jbrost/.local/share/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:1581
can't retry
github.com/icinga/icingadb/pkg/retry.WithBackoff
	/home/jbrost/dev/icingadb/pkg/retry/retry.go:42
github.com/icinga/icingadb/pkg/icingadb.(*DB).NamedBulkExec.func2.1.1
	/home/jbrost/dev/icingadb/pkg/icingadb/db.go:272
golang.org/x/sync/errgroup.(*Group).Go.func1
	/home/jbrost/.local/share/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:1581
exit status 1
```

**Comment by lippserd** [comment]
> Regarding possible bugs in the sync implementation: do we properly handle that Redis `HSCAN` may return elements multiple times?

No, we don't handle that and I think this may be the root cause of the duplicate key errors. If an element is yielded twice and already exists in the database, when calculating the delta it is first removed from the map of known elements and then added for insertion because it seems unknown, which leads to the duplicate key errors. One possible solution would be to invalidate/ignore known elements instead of removing them from the map. Or have something like a distinct channel which of course involves a new cache.
