### ISSUE TITLE
Log reconnects

### ISSUE THREAD

**Issue by lippserd** [Icinga/icingadb#351]
At the moment, Icinga DB only logs that it will retry reconnecting to the database (and Redis?). I think it makes sense to also log reconnects then. We could add a struct for optional args to the `retry.WithBackoff()` function which provides settings for `OnError` and `OnRetry` callbacks. The timeout should be moved there as well then.

**Comment by Al2Klimov** [comment]
1. I.e. not only the first error, but all/more?
2. Why a struct?
3. Why those settings? The callbacks already handle errors and retries by themselves. (They log the first error and silence the retries.)

**Comment by lippserd** [comment]
The idea with the struct and the callbacks is that the retry package is the only place that handles the error / retry conditions and not the consumers of that package. In the logs I would expect something like this:

```
Can't connect to database / Lost connection to database. Reason. Retrying
...
Reconnected to database after 1 minute 6 seconds.
...
```

For the sake of completeness, the `OnRetryableError` callback could have a variable that indicates whether it is the first error after the (re) connection.
