### ISSUE TITLE
Use Go generics (one nice day™)

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingadb#384]
... i.e. once

* [ ] Go v1.18

is available.

E.g.: pkg/com/bulker.go + pkg/com/entity_bulker.go

**Comment by julianbrost** [comment]
Another candidate: some of the places where we use the `Entity` interface right now. For example the database stuff could take channels of concrete entity types instead of reading the first item from the stream and deducing the type of the stream from it.

**Comment by Al2Klimov** [comment]
Wait.. "channels of concrete entity types"? What for? Wouldn't `T x; tableName(x)` be enough?

**Comment by julianbrost** [comment]
Enough for what?

My suggestion is to
1. get rid of the following as it has to spawn an extra goroutine to forward items just to peek at the first one: https://github.com/Icinga/icingadb/blob/0c9fb2f22f869046457f74c406d77da11e8ee4d8/pkg/com/com.go#L39-L82
2. ensure at compile-time that what currently is `chan Entity` is only used for one entity type as nothing will complain right now if you put in different entity types but just break at runtime.

**Comment by Al2Klimov** [comment]
1. Full ack.
2. Ah! I see.

**Comment by Al2Klimov** [comment]
> 1. get rid of the following as it has to spawn an extra goroutine to forward items just to peek at the first one:

I'm afraid generics and loops (over different types) don’t like each other.

**Comment by julianbrost** [comment]
Can you give an example of what doesn't work?
