### ISSUE TITLE
Schema migration: remove rows violating the constaints before adding the constraints

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icingadb#386]
The foreign key constraints added by #364 (bab2d80) may be violated by rows that already exist in the database (as the old code did not care about those constraints when inserting). 

The schema upgrade should be able to handle this, either by removing the rows in violation or setting the foreign keys to `NULL`. It's probably appropriate to do the first as the amount of information still left is of limited usefulness (something like "there was a state change, but we don't know anything about old state, new state, or output").

**Comment by lippserd** [comment]
This change was before the merge of #391, which requires a clean database. I think we can close this one.
