### ISSUE TITLE
Duplicate database entries

### ISSUE THREAD

**Issue by yhabteab** [Icinga/icingadb#419]
## Describe the bug

I just noticed that the number of my hosts are 2x more than the actual configured number and shows up twice in DB and db-web. See Screenshot!

**Database entries:**
```sql
MariaDB [icingadb]> SELECT COUNT(*) FROM host;
+----------+
| COUNT(*) |
+----------+
|     1006 |
+----------+
1 row in set (0.003 sec)
```

**DB WEB:**
<img width="1247" alt="Bildschirmfoto 2021-11-25 um 17 44 29" src="https://user-images.githubusercontent.com/57616252/143479334-6f399f7b-abd7-4a86-bade-b9160e69e6ba.png">

**IDO:**

<img width="1247" alt="Bildschirmfoto 2021-11-25 um 17 54 54" src="https://user-images.githubusercontent.com/57616252/143479419-0f6856f2-8af7-4b24-9097-80b1d959f482.png">

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Icinga DB version: `v1.0.0-rc2-dev`
* Icinga 2 version: `v2.13.2`
* Operating System and version: **Docker** `Debian GNU/Linux 11 (bullseye)`

**Comment by yhabteab** [comment]
**Services:**

<img width="458" alt="Bildschirmfoto 2021-11-25 um 18 09 46" src="https://user-images.githubusercontent.com/57616252/143481019-d264ecf9-21e9-448c-9722-b0a42f03d63e.png">

**IDO:**

<img width="458" alt="Bildschirmfoto 2021-11-25 um 18 11 31" src="https://user-images.githubusercontent.com/57616252/143481136-816094d2-b502-49b9-a350-4d24c0e97356.png">

**Comment by julianbrost** [comment]
Have you cleared the database when upgrading to RC2 (https://icinga.com/docs/icinga-db/latest/doc/04-Upgrading/)? If not, you'll end up with twice the objects with different `environment_id`s. To check, you can run `SELECT environment_id, COUNT(*) FROM host GROUP BY environment_id;`.
