### ISSUE TITLE
Primary key of icon_image, action_url, notes_url should not explicitly include the environment_id column

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icingadb#450]
These three tables have `PRIMARY KEY (environment_id, id)` and the comment for `id` says that the environment is not included in the hash:
https://github.com/Icinga/icingadb/blob/dece98e3e9e12bd592e2ea5d59ac6cb6f6a3ed23/schema/mysql/schema.sql#L722-L747

However, the code that generates the IDs actually includes the environment ID:
https://github.com/Icinga/icinga2/blob/fb2a58f177eddde909261e3da06894e28c889d3f/lib/icingadb/icingadb-objects.cpp#L682-L729

So we can just remove this irregularity from the schema without other code changes.

**Comment by lippserd** [comment]
Icinga DB Web Models have to be adjusted as well.
