### ISSUE TITLE
Consider moving away from JSON

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingadb#46]
... to a faster equivalent.

**Comment by Al2Klimov** [comment]
Alternatives:

* gob (with C/Go static lib or custom implementation in Icinga 2)
* custom binary protocol (Hello ObjectPacker!)
* ...

**Comment by dnsmichi** [comment]
Keep in mind that everything which is a custom implementation introduces bugs and possible breakdowns. I'm not a friend of changing this in Icinga 2 (again), where we move to tested and proven libraries instead. Personally I also don't like the raw Redis implementation in the RedisConnection class, I would never have merged that without OSMC pressure.

jm2c,
Michael

**Comment by Al2Klimov** [comment]
We've implemented 🚀 **a whole custom DSL** 🚀 in v2.0, so I don't see any problems in the custom Redis protocol I/O or in a custom binary protocol (which we already use in our checksums).

If nobody'd make any custom implementations, you wouldn't have any of these:

* OS
* browser/httpd
* mail client/server
* monitoring tool
* ...

**Comment by dnsmichi** [comment]
Since you already have learned how hard these things are to maintain, I can only strongly advise against following this route. Considering the planned release date with next week, this sounds like a total rewrite. Imho this shouldn't be part of the release candidate.

**Comment by Al2Klimov** [comment]
Don't worry, if it won't get done by that date, we'll just not include it.

**Comment by lippserd** [comment]
I think we had a little misunderstanding here because this is something for a future version.

**Comment by Al2Klimov** [comment]
Damn. The alternatives I described won't work.
