### ISSUE TITLE
Icingadb crashed because of notification_history text column

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icingadb#491]
## Describe the bug

Icingadb crashed most likely because the output of my check was too much but since it was fixed for #248, maybe this table was left out.

Error 1406: Data too long for column 'text' at row 1 can't perform "INSERT INTO notification_history...

## To Reproduce

Have a big notification text :)

## What fixed it

I changed the text column to medium text.
=> Icingadb started sucessfully

## Expected behavior

IcingaDb should not crash

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Icinga DB version: 1.0 rc2
* Icinga 2 version: 2.13.3
* Operating System and version: ubuntu 20.04

## Additional context

Best Regards
Nicolas

**Comment by julianbrost** [comment]
This was already addressed in #420, so it'll also be fixed in the next release.
