### ISSUE TITLE
Why does IcingaDB require a golang version which is not shipped with nearly any supported OS?

### ISSUE THREAD

**Issue by m4k5ym** [Icinga/icingadb#514]
## Describe the bug

IcingaDB requires golang with minimum version 1.18

According to your support matrix following operating systems are officially supported:

- CentOS 7 does provide 1.17.10
- RedHat Enterprise Linux 7 does provide 1.17.10
- RedHat Enterprise Linux 8 does provide 1.17.10
- Debian 10 does provide 1.11.6
- Debian 11 does provide 1.15.15
- Ubuntu Focal does provide 1.13
- Ubuntu Jammy does provide 1.18
- Suse Enterprise Linux 12 SP5 does provide 1.9.7 (hehe)
- Suse Enterprise Linux 15 SP3 does provide 1.18
- Suse Enterprise Linux 12 SP4 does provide 1.18

I mean in fact only three of your officially supported operating systems does provide golang in version >1.18 by its package manager. Any other officially supported operating system listed above does required a hand patched golang version just to build icingadb. Is there any reason for this? I also had to fix icingadb.spec file by hand because go flag `-buildvcs` seems to be something fancy new. Beside all this I don't even have a guarentee that my hand patched golang does work properly.

## To Reproduce

```
$ go version 
go version go1.17.10 linux/amd64
$ rpmbuild -ba icingadb.spec
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.Gki4Cd
+ umask 022
+ cd /home/(REDACTED FOR PRIVACY)/rpmbuild/BUILD
+ cd /home/(REDACTED FOR PRIVACY)/rpmbuild/BUILD
+ rm -rf icingadb-1.0.0
+ /usr/bin/gzip -dc /home/(REDACTED FOR PRIVACY)/rpmbuild/SOURCES/v1.0.0.tar.gz
+ /usr/bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd icingadb-1.0.0
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ go build -trimpath ./cmd/icingadb
go: downloading github.com/go-redis/redis/v8 v8.11.5
go: downloading github.com/okzk/sdnotify v0.0.0-20180710141335-d9becc38acbd
go: downloading github.com/pkg/errors v0.9.1
go: downloading go.uber.org/zap v1.21.0
go: downloading golang.org/x/sync v0.0.0-20210220032951-036812b2e83c
go: downloading github.com/jessevdk/go-flags v1.5.0
go: downloading github.com/go-sql-driver/mysql v1.6.0
go: downloading github.com/jmoiron/sqlx v1.3.5
go: downloading github.com/lib/pq v1.10.6
go: downloading github.com/google/uuid v1.3.0
go: downloading github.com/ssgreg/journald v1.0.0
go: downloading golang.org/x/exp v0.0.0-20210514180818-737f94c0881e
go: downloading github.com/cespare/xxhash/v2 v2.1.2
go: downloading github.com/dgryski/go-rendezvous v0.0.0-20200823014737-9f7001d12a5f
go: downloading github.com/creasty/defaults v1.6.0
go: downloading github.com/goccy/go-yaml v1.9.5-0.20211015131146-c6bcb8045535
go: downloading go.uber.org/atomic v1.7.0
go: downloading go.uber.org/multierr v1.6.0
go: downloading golang.org/x/sys v0.0.0-20211216021012-1d35b9e2eb4e
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: downloading github.com/fatih/color v1.10.0
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading github.com/mattn/go-isatty v0.0.12
# github.com/icinga/icingadb/pkg/version
pkg/version/version.go:55:32: info.Settings undefined (type *debug.BuildInfo has no field or method Settings)
note: module requires Go 1.18
# github.com/icinga/icingadb/pkg/com
pkg/com/atomic.go:6:15: syntax error: unexpected any, expecting ]
pkg/com/atomic.go:10:16: syntax error: unexpected [, expecting comma or )
pkg/com/atomic.go:18:16: syntax error: unexpected [, expecting comma or )
pkg/com/atomic.go:22:16: syntax error: unexpected [, expecting comma or )
pkg/com/atomic.go:30:16: syntax error: unexpected [, expecting comma or )
pkg/com/atomic.go:36:12: syntax error: unexpected any, expecting ]
pkg/com/bulker.go:15:29: syntax error: unexpected any, expecting ]
pkg/com/bulker.go:17:1: syntax error: unexpected type, expecting )
pkg/com/bulker.go:20:16: syntax error: unexpected [, expecting (
pkg/com/bulker.go:26:18: syntax error: unexpected [, expecting (
pkg/com/bulker.go:26:18: too many errors
note: module requires Go 1.18
error: Bad exit status from /var/tmp/rpm-tmp.Gki4Cd (%prep)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.Gki4Cd (%prep)
```

## Expected behavior

Being able to build IcingaDB on an officially supported operating system with its shipped golang version. If not possible provide me a way or idea to do so.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Icinga DB version: `hehe`
* Icinga 2 version: `none`
* Operating System and version: `CentOS Linux release 7.9.2009 (Core)`

## Additional context

**Comment by julianbrost** [comment]
We use language and toolchain features only available in newer Go versions, most notably generics (1.18) and modules (1.11) but probably many others. Also, the whole ecosystem adapts to new Go versions rather quickly and some libraries we use wouldn't work with old versions either.

For the operating systems we officially support, we provide binary packages that are ready to use.

**Comment by m4k5ym** [comment]
Yes but for RedHat Enterprise Linux are no packages available to the public. Therefore I have to build them myself. Thanks for your elaboration.
