### ISSUE TITLE
icingadb package not available on U18.04 LTS ?

### ISSUE THREAD

**Issue by BornTKill** [Icinga/icingadb#516]
Dear,

I cannot find icingadb in production ready source for bionic.
I only find RC in testing

root@icinga:~# apt-cache madison icingadb
  icingadb | 1.0.0~rc1-2.bionic | https://packages.icinga.com/ubuntu icinga-bionic-testing/main amd64 Packages
  icingadb | 1.0.0~rc1-1.bionic | https://packages.icinga.com/ubuntu icinga-bionic-testing/main amd64 Packages

Where is my mistake ?

**Comment by julianbrost** [comment]
We only provide packages for the latest two Ubuntu LTS versions and these are 20.04 and 22.04 now.
