### ISSUE TITLE
Add index on `customvar_flat.flatname`

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icingadb#523]
At the moment, there is no index on `customvar_flat.flatname`:

https://github.com/Icinga/icingadb/blob/a93da02eba179305340d2fbde970a25bd3d12480/schema/mysql/schema.sql#L979-L991

There probably should be one as this is used when filtering objects by custom vars in Web.

To be discussed: should there also be one for `customvar.name`? I don't know if anything would use this at the moment.

**Comment by lippserd** [comment]
@nilmerg What's your opinion here? Have you maybe even done tests for it?

**Comment by nilmerg** [comment]
Not specifically. We've noticed this during our *next sprint* tests.
