### ISSUE TITLE
Icinga2db Web show double object

### ISSUE THREAD

**Issue by ngyenhuukhoi** [Icinga/icingadb#532]
**## Describe the bug**

Icingadbweb show double object

**## To Reproduce**

Use Director and manually configure still get same behavior.

## Expected behavior

Dont show dupplicate object on Icingadbweb

## Your Environment

Include as many relevant details about the environment you experienced the problem in

I setup Icinga with 2 master and monitor agents via ssh. I did read https://github.com/Icinga/icingadb/issues/419 but This is new system.

* Icinga DB version:

Icinga DB version: v1.0.0

Build information:
  Go version: go1.18.1 (linux, amd64)
  Git commit: 0061888c404f87158d449d9b3ced82fca269a13b

System information:
  Platform: Ubuntu
  Platform version: 22.04.1 LTS (Jammy Jellyfish)

* Icinga 2 version:

 icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.5-1)
System information:
  Platform: Ubuntu
  Platform version: 22.04.1 LTS (Jammy Jellyfish)
  Kernel: Linux
  Kernel version: 5.15.0-50-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 11.2.0
  Build host: runner-hh8q3bz2-project-298-concurrent-0
  OpenSSL version: OpenSSL 3.0.2 15 Mar 2022

*Icingawebdb versions:

Icinga Web 2 Version | 2.11.1

PHP: 8.1.2

*Director version:
1.10.0

**Comment by julianbrost** [comment]
Can you please show the result of the following query in the `icingadb` database:
```sql
SELECT name, display_name, hex(environment_id) FROM host WHERE 'name-of-some-duplicate-here' IN (name, display_name);
```

Also, do you build a high-availability setup? Or did you at some point remove all icinga2 config and started from scratch there?

**Comment by ngyenhuukhoi** [comment]
> Can you please show the result of the following query in the `icingadb` database:
> 
> ```sql
> SELECT name, display_name, hex(environment_id) FROM host WHERE 'name-of-some-duplicate-here' IN (name, display_name);
> ```
> 
> Also, do you build a high-availability setup? Or did you at some point remove all icinga2 config and started from scratch there?

Hello:

MariaDB [icingadb]> SELECT name, display_name, hex(environment_id) FROM host WHERE 'name-of-some-duplicate-here' IN (name, display_name);
Empty set (0.001 sec)

**Comment by julianbrost** [comment]
`name-of-some-duplicate-here` was meant to be replaced with the name of some host that's shown twice.

> No, This is new set up with HA. It is run well some days ago.

Please check that the contents of `/var/lib/icinga2/icingadb.env` are identical on both machines, see also https://icinga.com/docs/icinga-db/latest/doc/05-Distributed-Setups/#environment-id

**Comment by ngyenhuukhoi** [comment]
> `name-of-some-duplicate-here` was meant to be replaced with the name of some host that's shown twice.
> 
> > No, This is new set up with HA. It is run well some days ago.
> 
> Please check that the contents of `/var/lib/icinga2/icingadb.env` are identical on both machines, see also https://icinga.com/docs/icinga-db/latest/doc/05-Distributed-Setups/#environment-id

Thank you. I will feedback soon

**Comment by ngyenhuukhoi** [comment]
Hello.
My database show dupplicate record for host and service.

Please check that the contents of /var/lib/icinga2/icingadb.env are identical on both machines
It showed different.


However.

**Comment by ngyenhuukhoi** [comment]
I will repopen if it happens again. Ty very much.
