### ISSUE TITLE
Percona-XtraDB-Cluster Support

### ISSUE THREAD

**Issue by 0xliam** [Icinga/icingadb#576]
Hi there,

We recently updated our Icinga installs to the latest version and I am looking to utilise IcingaDB - we have a  Percona SQL cluster running our installation of Icinga and IcingaWeb.

When trying to configure IcingaDB, we ran into the following issue:

```
2023-03-28T17:48:02.939+1100	INFO	icingadb	Starting Icinga DB
2023-03-28T17:48:02.939+1100	INFO	icingadb	Connecting to database at '10.52.1.3:3306'
2023-03-28T17:48:02.943+1100	INFO	icingadb	Connecting to Redis at 'localhost:6380'
2023-03-28T17:48:02.948+1100	INFO	icingadb	Starting history sync
2023-03-28T17:48:03.197+1100	INFO	heartbeat	Received Icinga heartbeat	{"environment": "ca54639388a8853d9c479dc11473b6c525ccc73c"}
2023-03-28T17:48:03.201+1100	FATAL	icingadb	Error 1105: Percona-XtraDB-Cluster doesn't recommend using SERIALIZABLE isolation with pxc_strict_mode = ENFORCING
can't start transaction
github.com/icinga/icingadb/pkg/icingadb.(*HA).realize.func1
	github.com/icinga/icingadb/pkg/icingadb/ha.go:253
github.com/icinga/icingadb/pkg/retry.WithBackoff
	github.com/icinga/icingadb/pkg/retry/retry.go:45
github.com/icinga/icingadb/pkg/icingadb.(*HA).realize
	github.com/icinga/icingadb/pkg/icingadb/ha.go:245
github.com/icinga/icingadb/pkg/icingadb.(*HA).controller
	github.com/icinga/icingadb/pkg/icingadb/ha.go:211
runtime.goexit
	runtime/asm_amd64.s:1594
can't retry
github.com/icinga/icingadb/pkg/retry.WithBackoff
	github.com/icinga/icingadb/pkg/retry/retry.go:64
github.com/icinga/icingadb/pkg/icingadb.(*HA).realize
	github.com/icinga/icingadb/pkg/icingadb/ha.go:245
github.com/icinga/icingadb/pkg/icingadb.(*HA).controller
	github.com/icinga/icingadb/pkg/icingadb/ha.go:211
runtime.goexit
	runtime/asm_amd64.s:1594
HA aborted
github.com/icinga/icingadb/pkg/icingadb.(*HA).abort.func1
	github.com/icinga/icingadb/pkg/icingadb/ha.go:128
sync.(*Once).doSlow
	sync/once.go:74
sync.(*Once).Do
	sync/once.go:65
github.com/icinga/icingadb/pkg/icingadb.(*HA).abort
	github.com/icinga/icingadb/pkg/icingadb/ha.go:126
github.com/icinga/icingadb/pkg/icingadb.(*HA).controller
	github.com/icinga/icingadb/pkg/icingadb/ha.go:218
runtime.goexit
	runtime/asm_amd64.s:1594
HA exited with an error
main.run
	github.com/icinga/icingadb/cmd/icingadb/main.go:335
main.main
	github.com/icinga/icingadb/cmd/icingadb/main.go:37
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_amd64.s:1594
```

It looks like this isn't a bug per se, but I am wondering if anyone has ran into this issue and how you solved it?

https://icinga.com/docs/icinga-db/latest/doc/05-Distributed-Setups/

It looks like the recommended way to achieve HA utilises one database server that both IcingaDB nodes write to, but we have a 3 node SQL cluster in different datacentres in the case that one of them fails. One of them is just a witness node, and the other two live beside an installation of IcingaWeb/Director.

**Comment by lippserd** [comment]
Hi @0xliam,

Thanks for the report. We'll evaluate whether we can switch to `REPEATABLE READ` isolation level w/o issues.

All the best,
Eric

**Comment by Al2Klimov** [comment]
Reproduced.

```
mysql> SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
ERROR 1105 (HY000): Percona-XtraDB-Cluster doesn't recommend using SERIALIZABLE isolation with pxc_strict_mode = ENFORCING
mysql>
```

https://docs.percona.com/percona-xtradb-cluster/5.7/install/docker.html is your friend.

**Comment by Al2Klimov** [comment]
> Thanks for the report. We'll evaluate whether we can switch to `REPEATABLE READ` isolation level w/o issues.

We can't **w/o issues**, we need the 40001 error to detect someone who committed faster than we did. But the good news are:

> SERIALIZABLE
>
> This level is like [REPEATABLE READ](https://dev.mysql.com/doc/refman/5.7/en/innodb-transaction-isolation-levels.html#isolevel_repeatable-read), but InnoDB implicitly converts all plain [SELECT](https://dev.mysql.com/doc/refman/5.7/en/select.html) statements to [SELECT ... LOCK IN SHARE MODE](https://dev.mysql.com/doc/refman/5.7/en/select.html) if [autocommit](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_autocommit) is disabled. (...)

> REPEATABLE READ
>
> This is the default isolation level for InnoDB. (...)

– https://dev.mysql.com/doc/refman/5.7/en/innodb-transaction-isolation-levels.html#isolevel_repeatable-read

So on MySQL we can emulate SERIALIZABLE tx via SELECT ... LOCK IN SHARE MODE. And on PXC...

##### Node 1

```
mysql> BEGIN;
Query OK, 0 rows affected (0.00 sec)

mysql> select * from lolcat LOCK IN SHARE MODE;
+----+
| id |
+----+
|  1 |
+----+
1 row in set (0.00 sec)

mysql> insert into lolcat values (2);
Query OK, 1 row affected (0.00 sec)

mysql> COMMIT;
Query OK, 0 rows affected (0.00 sec)

mysql>
```

##### Node 2

```
mysql> BEGIN;
Query OK, 0 rows affected (0.00 sec)

mysql> select * from lolcat LOCK IN SHARE MODE;
+----+
| id |
+----+
|  1 |
+----+
1 row in set (0.00 sec)

mysql> insert into lolcat values (2);
Query OK, 1 row affected (0.00 sec)

mysql> COMMIT;
ERROR 1213 (40001): WSREP detected deadlock/conflict and aborted the transaction. Try restarting the transaction
mysql>
```

... it purrs like a cat.
