### ISSUE TITLE
32-bit Packages

### ISSUE THREAD

**Issue by mjeheuer** [Icinga/icingadb#581]
Hi

I try to install Icinga2 with IcingaDB on my virtual Machine (**i386**), following the Guide on
https://icinga.com/docs/icinga-2/latest/doc/02-installation/01-Debian/
 
Unfortunately, the installation of the "DB Redis Package" aborts due to missing dependencies.
The installation of the "DB Redis Package" (_apt install icingadb-redis_) depends on the
"_icingadb-redis-server_" **which is not at the i386 package** included  (but it is in the amd64 Package!)
 
**i386 Package**
https://packages.icinga.com/debian/dists/icinga-bullseye/main/binary-i386/Packages
 
**amd64 Package**
https://packages.icinga.com/debian/dists/icinga-bullseye/main/binary-amd64/Packages

root@icinga2:~# apt install icingadb-redis
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass
Sie eine unmögliche Situation angefordert haben oder, wenn Sie die
Unstable-Distribution verwenden, dass einige erforderliche Pakete noch
nicht erstellt wurden oder Incoming noch nicht verlassen haben.
Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 icingadb-redis : Hängt ab von: icingadb-redis-server (< 7.0.5-1.bullseye.1~) ist aber nicht installierbar
                  Hängt ab von: icingadb-redis-server (>= 7.0.5-1.bullseye) ist aber nicht installierbar
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.
 

What can I do to solve the Problem?

Greetings
Michael

**Comment by lippserd** [comment]
Hi @mjeheuer,

We don't provide 32-bit packages yet. We'll keep you posted once they are ready.

All the best,
Eric

**Comment by htriem** [comment]
Version 7.0.12 of IcingaDB Redis now has been released for all supported OS, which includes 32-bit Debian as well. You should be able to get it from the official repositories at packages.icinga.com. Have fun using IcingaDB!
