### ISSUE TITLE
MySQL/MariaDB strict mode disabled by setting `sql_mode=ANSI_QUOTES`

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icingadb#611]
Looking into https://github.com/Icinga/icinga2/pull/9794#discussion_r1243404217 showed that this line has unintended side effects: 
https://github.com/Icinga/icingadb/blob/78fa223cab425a3a38e3fdbb32e53be6dfd9dfaf/pkg/config/database.go#L64

Add the following code to log the `sql_mode` after connecting to the database:

```diff
diff --git a/cmd/icingadb/main.go b/cmd/icingadb/main.go
index 1c22afc..f26a0a4 100644
--- a/cmd/icingadb/main.go
+++ b/cmd/icingadb/main.go
@@ -68,6 +68,10 @@ func run() int {
                if err != nil {
                        logger.Fatalf("%+v", errors.Wrap(err, "can't connect to database"))
                }
+
+               var sqlMode string
+               err = db.Get(&sqlMode, "SELECT @@sql_mode")
+               logger.Infow("sql mode", zap.String("sql_mode", sqlMode), zap.Error(err))
        }
 
        if err := db.CheckSchema(context.Background()); err != nil {
```

This will log:
```
sql mode        {"sql_mode": "ANSI_QUOTES"}
```

Now additionally comment out the line mentioned above that sets `sql_mode`, run it again and now it logs (and crashes shortly afterwards as MariaDB no longer understands the queries):
```
sql mode        {"sql_mode": "STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"}
```

So setting `sql_mode=ANSI_QUOTES` made MariaDB (and probably MySQL, but I didn't perform any extra tests with that) less strict. This will make it silently "fix" out-of-range values for numeric columns for example.

**Comment by lippserd** [comment]
I'll fix that.
