### ISSUE TITLE
HA config no longer working with 1.1.1 update

### ISSUE THREAD

**Issue by drapiti** [Icinga/icingadb#642]
Both masters are reporting Not responsible, but another instance is since updating to icingadb 1.1.1

Currently running postgres. The nodes are also occassionally crashing with the following:
![image](https://github.com/Icinga/icingadb/assets/4235359/21c7b8d3-b404-4bec-abf4-e7d2e8321996)

**Comment by drapiti** [comment]
This bug is quite urgent as it is compromising the whole cluster. Looks like some database constraint.

**Comment by gbin2265** [comment]
Do you upgrade te schema ? pgsql/upgrades/1.1.1.sql

One of the lines is : 
ALTER TABLE customvar_flat ALTER COLUMN flatvalue DROP NOT NULL;
