### ISSUE TITLE
Icingadb apt upgrade schema error

### ISSUE THREAD

**Issue by ment4field** [Icinga/icingadb#644]
## Describe the bug

Upgrading from  v.1.1.0 to 1.1.1 leads to the following error in the webinterface:

`It seems that Icinga DB is not running. Make sure Icinga DB is running and writing into the database.`  

icingadb service status:

```
× icingadb.service - Icinga DB
     Loaded: loaded (/lib/systemd/system/icingadb.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2023-08-14 15:29:11 CEST; 10min ago
    Process: 4893 ExecStart=/usr/sbin/icingadb --config /etc/icingadb/config.yml (code=exited, status=1/FAILURE)
   Main PID: 4893 (code=exited, status=1/FAILURE)
        CPU: 32ms

Aug 14 15:29:11 Ubuntu-Icinga2-V1 systemd[1]: Starting Icinga DB...
Aug 14 15:29:11 Ubuntu-Icinga2-V1 icingadb[4893]: Starting Icinga DB
Aug 14 15:29:11 Ubuntu-Icinga2-V1 icingadb[4893]: Connecting to database at 'localhost:0'
Aug 14 15:29:11 Ubuntu-Icinga2-V1 systemd[1]: Started Icinga DB.
Aug 14 15:29:11 Ubuntu-Icinga2-V1 icingadb[4893]: unexpected database schema version: v3 (expected v4), please make sure you h>
Aug 14 15:29:11 Ubuntu-Icinga2-V1 systemd[1]: icingadb.service: Main process exited, code=exited, status=1/FAILURE
Aug 14 15:29:11 Ubuntu-Icinga2-V1 systemd[1]: icingadb.service: Failed with result 'exit-code'.
```

## To Reproduce

1. install icinga2 using the webguide 4 days ago (mariadb).
2. Import schema.sql in mariadb as per guide
3. check icingadb package version (1.1.0) 
4. apt update
5. apt upgrade  

## Expected behavior
Running database without error or information on package upgrade in terminal/webinterface to the database schema upgrade guide or automatic schema upgrade

## Your Environment

* Icinga DB version: 1.1.1-1+ubuntu22.04 (upgraded from 1.1.0)  
* Icinga 2 version: 2.14.0-1+ubuntu22.04
* Operating System and version: ubuntu22.04

**Comment by julianbrost** [comment]
The full message (your `systemctl status` output only shows a truncated line) is:

> unexpected database schema version: v3 (expected v4), please make sure you have applied all database migrations after upgrading Icinga DB

Also, the [release announcement](https://icinga.com/blog/2023/08/09/releasing-icinga-db-1-1-1/) and the [upgrading documentation](https://icinga.com/docs/icinga-db/latest/doc/04-Upgrading/#upgrading-to-icinga-db-v111) mention that a schema upgrade has to be applied.

**Comment by oxzi** [comment]
> How do you do apply it? I have the databases in PostgreSQL, just applying it with `psql -d icingadb -a -f /usr/share/icingadb/schema/mysql/upgrades/1.2.0.sql` results in

Please take a look at the path of the schema upgrade. It seems like you want to apply the `mysql` schema upgrade for your PsotgreSQL database.

For future problems, please create a new issue and don't reuse an old one.

**Comment by Artim96** [comment]
Sorry about that, it's just too warm to think...
