### ISSUE TITLE
Crash after "Resource deadlock avoided"

### ISSUE THREAD

**Issue by epinter** [Icinga/icingadb#651]
## Describe the bug

IcingaDB daemon crashes after this error happens: "Resource deadlock avoided" (log attached).

## To Reproduce

1. Start icingadb service and wait the crash

## Expected behavior

I expect the service handle the error.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Icinga DB version: 1.1.1-1+debian10
* Icinga 2 version: 2.14.0-1+debian10
* Operating System and version: Debian 10
* Database: MariaDB 10.3.39-0+deb10u1 (Galera cluster)

## Additional context

The database cluster has 3 nodes (the two Icinga masters, and another standby server for database redundancy). I run Icinga in this cluster with MariaDB since 2016, never had a problem with IDO. The problem started to happen as soon as I started icingadb for the first time. The error happens while the cluster is under low load.

The crashes happens on both masters.

- Error:
`icingadb[1660]: Error 1180 (HY000): Got error 35 "Resource deadlock avoided" during COMMIT#012can't perform "INSERT INTO \"history\" (\"event_time\", \"event_type\", \"id\", \"object_type\", \"host_id\", \"service_id\", \"state_history_id\", \"environment_id\", \"endpoint_id\") VALUES (:event_time,:event_type,:id,:object_type,:host_id,:service_id,:state_history_id,:environment_id,:endpoint_id) ON DUPLICATE KEY UPDATE \"id\" = VALUES(\"id\")"#012github.com/icinga/icingadb/internal.CantPerformQuery#012#011github.com/icinga/icingadb/internal/internal.go:30#012github.com/icinga/icingadb/pkg/icingadb.(*DB).NamedBulkExec.func1.1.1.1#012#011github.com/icinga/icingadb/pkg/icingadb/db.go:391#012github.com/icinga/icingadb/pkg/retry.WithBackoff#012#011github.com/icinga/icingadb/pkg/retry/retry.go:49#012github.com/icinga/icingadb/pkg/icingadb.(*DB).NamedBulkExec.func1.1.1#012#011github.com/icinga/icingadb/pkg/icingadb/db.go:386#012golang.org/x/sync/errgroup.(*Group).Go.func1#012#011golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75#012runtime.goexit#012#011runtime/asm_amd64.s:1598#012can't retry#012github.com/icinga/icingadb/pkg/retry.WithBackoff#012#011github.com/icinga/icingadb/pkg/retry/retry.go:68#012github.com/icinga/icingadb/pkg/icingadb
[icinga-log-deadlock.txt](https://github.com/Icinga/icingadb/files/12720309/icinga-log-deadlock.txt)
.(*DB).NamedBulkExec.func1.1.1#012#011github.com/icinga/icingadb/pkg/icingadb/db.go:386#012golang.org/x/sync/errgroup.(*Group).Go.func1#012#011golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75#012runtime.goexit#012#011runtime/asm_amd64.s:1598`

[icinga-log-deadlock.txt](https://github.com/Icinga/icingadb/files/12720317/icinga-log-deadlock.txt)

**Comment by epinter** [comment]
[icinga-log-deadlock.txt](https://github.com/Icinga/icingadb/files/12720311/icinga-log-deadlock.txt)

**Comment by epinter** [comment]
A Virtual IP configured with Keepalived fixed the problem. Maybe there's something that can be improved in IcingaDB to avoid the need of a VIP in this cases...

**Comment by oxzi** [comment]
Thank you for creating this issue.

> I run Icinga in this cluster with MariaDB since 2016, never had a problem with IDO. The problem started to happen as soon as I started icingadb for the first time.

This is most likely due to the fact that the old IDO used a single database connection, while Icinga DB internally holds multiple database connections, which then went to different servers within the Galera cluster.
As a result, successive queries were sent to different servers, which then led to conflicts.

Please take a look at #577, where Galera-related issues are being discussed.
