### ISSUE TITLE
Missing handling for HTTP 503 from Icinga 2 API in integration tests

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icingadb#685]
Currently, the integration tests are failing quite frequently due to the Icinga 2 API returning HTTP 503 responses:

```
    sla_test.go:237: 
        	Error Trace:	sla_test.go:237
        	            				sla_test.go:367
        	Error:      	Not equal: 
        	            	expected: 200
        	            	actual  : 503
        	Test:       	TestSla/DowntimeEvents/Fixed/Expire
        	Messages:   	schedule-downtime
```

Examples for pipelines with this or similar errors on GitHub Actions: [1](https://github.com/Icinga/icingadb/actions/runs/8230208850/job/22502974943?pr=670) [2](https://github.com/Icinga/icingadb/actions/runs/8138758314/job/22502689501?pr=682) [3](https://github.com/Icinga/icingadb/actions/runs/8047117395/job/22502706814?pr=680) [4](https://github.com/Icinga/icingadb/actions/runs/8047117395/job/22502707172?pr=680)

This is probably a result of https://github.com/Icinga/icinga2/pull/9445, so the tests should be adapted to handle this.

**Comment by yhabteab** [comment]
I think this is a bug and a blocker, as otherwise all other PRs suffer from this issue.

**Comment by Al2Klimov** [comment]
## TODO

* [ ] fix our dep github.com/icinga/icinga-testing (in its upstream)
* [ ] bump its "version" here
