### ISSUE TITLE
Update to `github.com/redis/go-redis/v9`

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icingadb#708]
I just noticed that we're using `github.com/go-redis/redis/v8` while [`v9`](https://github.com/redis/go-redis/releases/tag/v9.0.0) exists for over a year and `v8` doesn't seem to get any further updates. Looks like this change isn't picked up by dependabot.

**Comment by oxzi** [comment]
Btw, same goes for `github.com/vbauerster/mpb/v6` used in `icingadb-migrate`, where also a `v8` is already available. We should check package updates for Go module major version suffix bumps.
