### ISSUE TITLE
Document `retention.count` & `retention.interval` configs

### ISSUE THREAD

**Issue by yhabteab** [Icinga/icingadb#717]
## Describe the bug

Currently the default retention delete counter happens to be `5000` and occasionally causes some strange SQL errors (**Error 1206: The total number of locks exceeds the size of the lock table**). We should reduce these numbers to a much smaller number like `500` or maybe even smaller. [`MySQL`](https://dev.mysql.com/doc/mysql-errors/8.0/en/server-error-reference.html#error_er_lock_table_full) also suggests splitting such large operations into smaller chunks instead of tweaking system variables like the `innodb_buffer_pool_size` to get around this problem.

PS: We should also document the `retention.count` option [here](https://icinga.com/docs/icinga-db/latest/doc/03-Configuration/#retention).

refs https://github.com/Icinga/icingadb/issues/618

**Comment by lippserd** [comment]
I'm totally in favor of documenting `retention.count` but not the reducing/(increasing) part. `5000` is already a really small chunk. We only have one report where the user made a configuration mistake. And the default `innodb_buffer_pool_size` value is a joke for production systems and should be increased anyway. Also as locks come and go, retrying retention statements should be fine.
