### ISSUE TITLE
Default `database.options` gets overridden & fails config validation

### ISSUE THREAD

**Issue by yhabteab** [Icinga/icingadb#726]
## Describe the bug

We need to comment out [`database.options`](https://github.com/Icinga/icingadb/blob/main/config.example.yml#L28) until the `goccy/go-yaml` [upstream](https://github.com/goccy/go-yaml/pull/442) branch is merged and released. Otherwise, Icinga DB fails to start with the following validation error.
```bash
~/Workspace/go/icingadb (missing-history-index ✗) go run cmd/icingadb/main.go --config config.example.yml
invalid configuration: max_connections cannot be 0. Configure a value greater than zero, or use -1 for no connection limit
exit status 2
```

**Comment by oxzi** [comment]
For the record, I build an Icinga DB version with @yhabteab's patch against `go-yaml` which solved the issue.

However, as a workaround for the upcoming release I just created #731.
