### ISSUE TITLE
IcingaDB HA crashs every night after upgrade to 1.2.0

### ISSUE THREAD

**Issue by TheCry** [Icinga/icingadb#742]
## Describe the bug

Every night the IcingaDB HA crashs

## Expected behavior

No downtime like before the upgrade

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Icinga DB version: 1.2.0 
* Icinga DB Web: 1.1.2
* Icinga 2 version: 2.14.2
* Operating System and version: Debian 11

## Additional context

We have a HA cluster with an external ICINGA Webui server.
On Monday, I'd upgraded IcingaDB to 1.2.0. Everything is installed via package manager.
After upgrading the packages, I imported the SQL file "1.2.0.sql" from one of the two ICINGA nodes. This was completed without any errors. Subsequently, the Icinga DB daemon was restarted on both nodes.
Icinga was running again and everything looked good.
On Tuesday morning, WebUi said that "IcingaDB" no longer writes data. 
I have now stopped the daemon of "IcingaDB" and "IcingaDB-Redis" on both nodes and then restarted. Unfortunately, the problem remains. Every night at about 03:15 a.m. the "IcingaDB daemon" crashed. In the hournal I always find the same message:

```
  Apr 17 03:06:09 Node1 icingadb[1952232]: Handing over
Apr 17 03:06:10 Node1 icingadb[1952232]: runtime-updates: Can't execute Redis pipeline
Apr 17 03:13:00 Node1 icingadb[1952232]: retry deadline exceeded
                                            github.com/icinga/icingadb/pkg/icingadb.(*HA).controller
                                                    github.com/icinga/icingadb/pkg/icingadb/ha.go:163
                                            runtime.goexit
                                                    runtime/asm_amd64.s:1695
                                            HA aborted
                                            github.com/icinga/icingadb/pkg/icingadb.(*HA).abort.func1
                                                    github.com/icinga/icingadb/pkg/icingadb/ha.go:131
                                            sync.(*Once).doSlow
                                                    sync/once.go:74
                                            sync.(*Once).Do
                                                    sync/once.go:65
                                            github.com/icinga/icingadb/pkg/icingadb.(*HA).abort
                                                    github.com/icinga/icingadb/pkg/icingadb/ha.go:129
                                            github.com/icinga/icingadb/pkg/icingadb.(*HA).controller
                                                    github.com/icinga/icingadb/pkg/icingadb/ha.go:163
                                            runtime.goexit
                                                    runtime/asm_amd64.s:1695
                                            HA exited with an error
                                            main.run
                                                    github.com/icinga/icingadb/cmd/icingadb/main.go:335
                                            main.main
                                                    github.com/icinga/icingadb/cmd/icingadb/main.go:37
                                            runtime.main
                                                    runtime/proc.go:271
                                            runtime.goexit
                                                    runtime/asm_amd64.s:1695
```

At this time, Bareo's fuses are running. However, these had no effect on it until before the upgrade.
Regards
Sascha

**Comment by oxzi** [comment]
Thanks for coming forward with this issue. Based on your provided information and what was within the stack trace, it seems like your Redis instance is unavailable or at least unhealthy. The error "_runtime-updates: Can't execute Redis pipeline_" ([source](https://github.com/Icinga/icingadb/blob/v1.2.0/pkg/icingadb/runtime_updates.go#L281-L282)) indicates this.

One change between v1.1.1 and v.1.2.0 was 81085c04a42a67527559a611f8129af26afbfb13, effectively don't retrying a failed HA but giving up after five minutes. Thus, it might be the case that this error was already there before upgrading Icinga DB to v1.2.0, but just invisible.

Speaking of visibility, what is the other Icinga DB node doing? Could you please provide more extensive logs extending further into the past, from both Icinga DB nodes include their Redis? Please evaluate the [logging level](https://icinga.com/docs/icinga-db/latest/doc/03-Configuration/#logging-configuration) - all components included - to `debug` and restart the Icinga DBs before the next expected crash.

As there are additional information being logged as [fields](https://www.freedesktop.org/software/systemd/man/latest/systemd.journal-fields.html) when using the `systemd-journald` output, you might wanna include those in your journalctl's [output format](https://manpages.debian.org/bookworm/systemd/journalctl.1.en.html#OUTPUT_OPTIONS), e.g., by using `journalctl -o json`.

What does the Bareos exactly do at this moment? Does it interact with the Redis instance or reconfigures the network? Is something else altering the system state at this moment?

**Comment by TheCry** [comment]
`[error_icingadb_Node1.log](https://github.com/Icinga/icingadb/files/15023144/error_icingadb_Node1.log)`
I don't think so. If only that is to the database of IcingaDB. As written.. Everything was stable until before the upgrade
IcingaDB's database runs on IcingaWeb's server. 
So a remote database for the 2 nodes in the HA cluster. It's a MariaDB (V 10.11.7).
There are no abnormalities there.
I've now adjusted the config.yml and restarted the IcingaDB daemon.

I'll attach the JSON output of both nodes of the last 72 hours to the ticket
[error_icingadb_Node1.log](https://github.com/Icinga/icingadb/files/15023148/error_icingadb_Node1.log)

[error_icingadb_Node2.log](https://github.com/Icinga/icingadb/files/15023145/error_icingadb_Node2.log)

**Comment by oxzi** [comment]
Thanks for providing those logs. However, it seems like the logging level is too high.

A small inspection with
```
jq -s 'sort_by(.__REALTIME_TIMESTAMP | tonumber) | .[] | [._HOSTNAME, (.__REALTIME_TIMESTAMP | tonumber | . / 1000000 | strftime("%x %X %Z")), .MESSAGE, .ICINGADB_ERROR]' < error_icingadb_Node?.log
```
only reveals `"context canceled"` errors, but it misses why the context was canceled. Thus, we have to wait for the next error and have a look at the debug logs then.

**Comment by oxzi** [comment]
Please excuse the second post, but could you include all available log levels/priorities in your output. I misread the `--priority` flag in your prior post.

>If a JSON log with this call is sufficient: `journalctl --boot --reverse --priority=emerg.. err --since=-72h --unit="icingadb.service" -o json`

Please set `--priority 0..7` or `--priority emerg..debug`.

**Comment by TheCry** [comment]
No problem... 
The logs will be huge if I start the DEBUG level until tomorrow. I attach the new logs "--priority emerg..debug"
[error_icingadb_Node1_and_2.zip](https://github.com/Icinga/icingadb/files/15025390/error_icingadb_Node1_and_2.zip)

**Comment by oxzi** [comment]
Thanks a lot. Regardless the size, I would like to inspect tomorrow's logs after the crash. Maybe you can reduce it to round about 30m before the crash.

**Comment by TheCry** [comment]
Good morning. I have great news.. There was no outage tonight. 
I also had the Bareos backup disabled for the 3 servers yesterday.
So I tried to reproduce the bug this morning. And it's my database backupscript that triggers the error when dumping the databases. I have attached the logs of both nodes (1 hour backwards) with debug information.
I have my backup script for the databases attached, because I just don't understand that it didn't cause any problems before the upgrade.
The icingadb database is 47GB in size. The retention is set as follows:
history-days: 90
SLA-Days: 180

Here are the logs and the script:
[error_icingadb_node1_and_2-1h.zip](https://github.com/Icinga/icingadb/files/15033558/error_icingadb_node1_and_2-1h.zip)
[DatabaseBackupScript.txt](https://github.com/Icinga/icingadb/files/15033577/DatabaseBackupScript.txt)

**Comment by oxzi** [comment]
Thanks for your detailed report, your logs and your script. Based on your experiment, I would guess that your backup script is taking longer than the magic five minutes that Icinga DB now retires every database error since the latest v1.2.0 release. When it reaches this limit and there is still a LOCK from the `mysqldump`, Icinga DB exits.

Earlier you wrote that you have configured your database to "not lock". How did you do this? Could you try configuring your mysqldump command to not LOCK or use transactions as described in  [this StackOverflow thread](https://stackoverflow.com/questions/104612/run-mysqldump-without-locking-tables)? If everything else fails, you might wanna consider stopping and restarting Icinga DB during the time of your backup?

**Comment by TheCry** [comment]
Es scheint so als ob mysqldump bei Default einen lock setzt. Ich habe es in meinem script nicht gemacht.. Nun habe ich einen Dump mit "--single-transaction=TRUE" erstellt und es kam zu keinem Ausfall..
Vielen Dank für Deine Unterstützung.

**Comment by oxzi** [comment]
I am glad to hear that. Unless you have an idea what to change, please feel free to close this issue.

**Comment by TheCry** [comment]
No - ICINGA is going great and I'm more than happy with it. Thanks again for your support, as it should have been in the forum. The only thing I didn't think about was the database dump at first
