### ISSUE TITLE
Do not write history/state/overdue when not reponsible

### ISSUE THREAD

**Issue by N-o-X** [Icinga/icingadb#85]
Concept:
- Only the active Icinga DB writes into MySQL
- The active instance also writes the last Redis stream ID into something like a `history_state` table
- The inactive instance removes everything before the stream ID plus a time buffer from its own stream (using https://redis.io/commands/xrange)

**Comment by stupiddr** [comment]
@N-o-X 
Curious on this, is this to a fix an issue where the inactive icingadb instance is marking checks as overdue when they infact are not?
Currently running into an issue with this, wondering if thats what this is intended for or if I should create a different issue.
Thanks!

**Comment by N-o-X** [comment]
Hi @stupiddr,

this issues didn't have such a bug in mind, it's just here to lower the amount of writes to MySQL.
Your problem is indeed new to me. It would be great, if you could create a new issues on that topic.

Thanks and greetings
Noah

**Comment by lippserd** [comment]
RC 2 does nothing when not responsible. Closing here.
